[package]
name = "context"
version = "0.1.1"
authors = ["Y. T. Chung <zonyitoo@gmail.com>"]
license = "MIT/ISC"
repository = "https://github.com/zonyitoo/context-rs"
description = "Context in Rust"
readme = "README.md"
build = "build.rs"
keywords = ["context"]

[build-dependencies]
gcc = "*"
log = "*"

[dependencies]
mmap = "*"
