[package]
name = "context"
version = "0.1.3"
authors = ["Y. T. Chung <zonyitoo@gmail.com>"]
license = "MIT/ISC"
repository = "https://github.com/zonyitoo/context-rs"
description = "Context in Rust"
readme = "README.md"
build = "build.rs"
links = "ctxswtch"
keywords = ["context"]

[build-dependencies]
gcc = "^0.3.12"
log = "^0.3.1"

[dependencies]
libc = "^0.1.10"
log = "^0.3.1"
memmap = "^0.2"

