[package]
name = "context"
version = "0.1.2"
authors = ["Y. T. Chung <zonyitoo@gmail.com>"]
license = "MIT/ISC"
repository = "https://github.com/zonyitoo/context-rs"
description = "Context in Rust"
readme = "README.md"
build = "build.rs"
keywords = ["context"]

[build-dependencies]
gcc = "^0.3.12"
log = "^0.3.1"

[dependencies]
mmap = "^0.1.1"
